-- Recrée la table avec la colonne statut
drop table if exists exam_aspirant;

create table exam_aspirant (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  score int,
  correct int,
  total int,
  time_left int,
  finished boolean default false,
  eliminated boolean default false,
  answers jsonb,
  statut text default 'attente'
);

alter table exam_aspirant enable row level security;

create policy "insert_exam" on exam_aspirant
  for insert to anon with check (true);

create policy "read_exam" on exam_aspirant
  for select to anon using (true);

create policy "update_statut" on exam_aspirant
  for update to anon
  using (true)
  with check (true);

-- ============================================================
-- EXAMEN ADEPTE
-- ============================================================
drop table if exists exam_adepte;

create table exam_adepte (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  name text not null,
  score int,
  correct int,
  total int,
  time_left int,
  finished boolean default false,
  eliminated boolean default false,
  answers jsonb,
  statut text default 'attente'
);

alter table exam_adepte enable row level security;

create policy "insert_exam_adepte" on exam_adepte
  for insert to anon with check (true);

create policy "read_exam_adepte" on exam_adepte
  for select to anon using (true);

create policy "update_statut_adepte" on exam_adepte
  for update to anon
  using (true)
  with check (true);

-- ============================================================
-- CAS CLINIQUES — ÉPREUVE ORALE (résultats de validation)
-- ============================================================
drop table if exists cas_cliniques_resultats;

create table cas_cliniques_resultats (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  candidate text not null,
  exam_type text,
  cas_titre text,
  score int,
  total int,
  reussi boolean,
  elements_valides jsonb
);

alter table cas_cliniques_resultats enable row level security;

create policy "insert_cas_cliniques" on cas_cliniques_resultats
  for insert to anon with check (true);

create policy "read_cas_cliniques" on cas_cliniques_resultats
  for select to anon using (true);
